name: Build/Upload Edge
on:
  push:
    branches:
      - 'edge'
    tags:
      - '!*'
  pull_request:
    branches:
      - 'edge'
    tags:
      - '!*'
jobs:
  test:
    name: Test on ${{ matrix.os }} with JDK 11.0.4
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11.0.4
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Set up Ant (Win)
      run: choco install ant
      if: startsWith(matrix.os, 'windows-')
    - name: Set up Ant (macOS)
      run: brew install ant
      if: startsWith(matrix.os, 'macOS-')
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml test
  build:
    name: Build and upload on ubuntu-latest with JDK 11.0.4
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11.0.4
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Set up Ant script
      run: |
        sed -i 's/"version" value="[0-9.]+"/"version" value="edge"/g' build.xml
        echo $?
        cat build.xml
    - name: Distclean with Ant
      run: ant -noinput -buildfile build.xml distclean
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml dist
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: PhantomBot-edge
        path: dist/PhantomBot-edge
