name: Build/Upload Edge
on:
  push:
    branches:
      - 'edge'
    tags:
      - '!*'
  pull_request:
    branches:
      - 'edge'
    tags:
      - '!*'
jobs:
  buildtest:
    name: Test Build on ${{ matrix.os }} with JDK 11.0.4
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Set up JDK 11.0.4
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Set up Ant (Linux)
      run: sudo apt-get install ant
      if: startsWith(matrix.os, 'ubuntu-')
    - name: Set up Ant (Windows)
      run: choco install ant
      if: startsWith(matrix.os, 'windows-')
    - name: Set up Ant (macOS)
      run: brew install ant
      if: startsWith(matrix.os, 'macOS-')
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml test
  build:
    name: Build and upload on ubuntu-latest with JDK 11.0.4
    runs-on: ubuntu-latest
    needs: buildtest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Set up JDK 11.0.4
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Set up Ant
      run: sudo apt-get install ant
    - name: Prep Ant script
      run: |
        sed -i -r 's/"version" value="[0-9.]+"/"version" value="edge"/' build.xml
        echo $?
        cat build.xml
    - name: Build with Ant
      run: ant -noinput -Dbuildtype=edge_build -buildfile build.xml dist
    - name: Prep Artifacts
      run: |
        mkdir dist/PhantomBot-edge-lin
        cp -r dist/PhantomBot-edge dist/PhantomBot-edge-lin
        rm -rfv dist/PhantomBot-edge-lin/java-runtime
        rm -rfv dist/PhantomBot-edge-lin/java-runtime-macos
        rm -rfv dist/PhantomBot-edge-lin/launch.bat
        mkdir dist/PhantomBot-edge-win
        cp -r dist/PhantomBot-edge dist/PhantomBot-edge-win
        rm -rfv dist/PhantomBot-edge-win/java-runtime-linux
        rm -rfv dist/PhantomBot-edge-win/java-runtime-macos
        rm -rfv dist/PhantomBot-edge-win/launch.sh
        rm -rfv dist/PhantomBot-edge-win/launch-service.sh
        mkdir dist/PhantomBot-edge-mac
        cp -r dist/PhantomBot-edge dist/PhantomBot-edge-mac
        rm -rfv dist/PhantomBot-edge-mac/java-runtime-linux
        rm -rfv dist/PhantomBot-edge-mac/java-runtime
        rm -rfv dist/PhantomBot-edge-mac/launch.bat
        mkdir dist/PhantomBot-edge-arm
        cp -r dist/PhantomBot-edge dist/PhantomBot-edge-arm
        rm -rfv dist/PhantomBot-edge-arm/java-runtime-linux
        rm -rfv dist/PhantomBot-edge-arm/java-runtime
        rm -rfv dist/PhantomBot-edge-arm/java-runtime-macos
        rm -rfv dist/PhantomBot-edge-arm/launch.bat
    - name: Upload Artifact (Full)
      uses: actions/upload-artifact@v1
      with:
        name: PhantomBot-edge
        path: dist/PhantomBot-edge
    - name: Upload Artifact (Linux)
      uses: actions/upload-artifact@v1
      with:
        name: PhantomBot-edge-lin
        path: dist/PhantomBot-edge-lin
    - name: Upload Artifact (Windows)
      uses: actions/upload-artifact@v1
      with:
        name: PhantomBot-edge-win
        path: dist/PhantomBot-edge-win
    - name: Upload Artifact (macOS)
      uses: actions/upload-artifact@v1
      with:
        name: PhantomBot-edge-mac
        path: dist/PhantomBot-edge-mac
    - name: Upload Artifact (ARM)
      uses: actions/upload-artifact@v1
      with:
        name: PhantomBot-edge-arm
        path: dist/PhantomBot-edge-arm
